services:
  - type: web
    name: resume-analyzer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: GROQ_API_KEY
        sync: false
      - key: OCR_SPACE_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
